# Generated by Django 5.1 on 2024-09-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_posts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
